name: Setup node environment
description: Checks out the repo, sets up cache, installs dependencies enables cancel workflow

inputs:
  version:
    description: The node version to use
    required: false
    default: '18.x'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.32.0

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
