on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Release
        uses: cycjimmy/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}