name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # 0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install Node dependencies
        uses: demvsystems/eslint-config-liebe/.github/actions/setup-node@0829b4321d2b14aed6f58e33c47fa9f624dbb01c # main

      - run: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
