name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/*'
      - '.changeset/*.md'
  workflow_dispatch:
    inputs:
      forceRelease:
        description: 'Forces to execute the release action without validating if theres a new version (true/false)'     
        required: true
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Install Node dependencies
        uses: demvsystems/eslint-config-liebe/.github/actions/setup-node@main

      - if: github.event.inputs.forceRelease != 'true'
        name: Check Version
        id: version
        run: |
          echo ::set-output name=changes::$(pnpm exec changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')

      - if: steps.version.outputs.changes == 'true' && github.event.inputs.forceRelease != 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version

      - if: steps.version.outputs.changes == 'true' || github.event.inputs.forceRelease == 'true'
        name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
