name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Install Node dependencies
        uses: demvsystems/eslint-config-liebe/.github/actions/setup-node@main

      - name: Check Version
        id: version
        run: |
          echo ::set-output name=changes::$(pnpm exec changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')

      - if: steps.version.outputs.changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version

      - if: steps.version.outputs.changes == 'true'
        name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          UPDATE_TEMPLATE_SSH_KEY: ${{ secrets.UPDATE_TEMPLATE_SSH_KEY }}
