name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  lintAndTest:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install Node dependencies
        uses: demvsystems/eslint-config-liebe/.github/actions/setup-node@main

      - run: pnpm release:dry
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
