name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  lintAndTest:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Install Node dependencies
        uses: demvsystems/eslint-config-liebe/.github/actions/setup-node@main

      # - run: pnpm exec turbo run test lint
